export const Products = [
	{
		ProductID: '1',
		ProductTitle: 'Classic Navy Suit',
		description: 'A classic navy suit suitable for any occasion.',
		Price: 199,
		currency: 'USD',
		category: 'Suits',
		collection: 'Classic',
		ImageUrl: '/Img/productImages/classic-navy-suit.jpg',
		images: [
			'/Img/productImages/prodOne.png',
			'https://example.com/classic-navy-suit2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L', 'XL'],
		colors: ['Navy'],
		ProductReviewCount: 78,
		ProductStarCount: 3,
		DiscountPrice: 149,
		stock: 50,
	},
	{
		ProductID: '2',
		ProductTitle: 'Slim Fit Charcoal Suit',
		description: 'A slim fit charcoal suit for a modern look.',
		Price: 249,
		currency: 'USD',
		category: 'Suits',
		collection: 'Vintage',
		ImageUrl: '/Img/productImages/slim-fit-charcoal-suit.png',
		images: [
			'https://example.com/slim-charcoal-suit1.jpg',
			'https://example.com/slim-charcoal-suit2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Charcoal'],
		ProductReviewCount: 42,
		ProductStarCount: 2,
		DiscountPrice: 189,
		stock: 30,
	},
	{
		ProductID: '3',
		ProductTitle: 'Double-Breasted Pinstripe Suit',
		description: 'A double-breasted pinstripe suit for a vintage look.',
		Price: 299,
		currency: 'USD',
		category: 'Suits',
		collection: 'Vintage',
		ImageUrl: '/Img/productImages/double-breasted-pinstripe-suit.png',
		images: [
			'https://example.com/pinstripe-suit1.jpg',
			'https://example.com/pinstripe-suit2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Black'],
		ProductReviewCount: 63,
		ProductStarCount: 4,
		DiscountPrice: 259,
		stock: 20,
	},
	{
		ProductID: '4',
		ProductTitle: 'Linen Summer Suit',
		description: 'A lightweight linen suit perfect for summer.',
		Price: 179,
		currency: 'USD',
		category: 'Suits',
		collection: 'Modern',
		ImageUrl: '/Img/productImages/linen-summer-suit.png',
		images: [
			'https://example.com/linen-summer-suit1.jpg',
			'https://example.com/linen-summer-suit2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Beige'],
		ProductReviewCount: 57,
		ProductStarCount: 5,
		DiscountPrice: 139,
		stock: 40,
	},
	{
		ProductID: '5',
		ProductTitle: 'Tuxedo Suit',
		description: 'A classic tuxedo suit for formal events.',
		Price: 349,
		currency: 'USD',
		category: 'Suits',
		collection: 'Classic',
		ImageUrl: '/Img/productImages/tuxedo-suit.png',
		images: [
			'https://example.com/tuxedo-suit1.jpg',
			'https://example.com/tuxedo-suit2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Black'],
		ProductReviewCount: 89,
		ProductStarCount: 4,
		DiscountPrice: 200,
		stock: 25,
	},
	{
		ProductID: '6',
		ProductTitle: 'Plaid Business Suit',
		description:
			'A stylish plaid business suit for professional settings.',
		Price: 279,
		currency: 'USD',
		category: 'Suits',
		collection: 'Business',
		ImageUrl: '/Img/productImages/plaid-business-suit.png',
		images: [
			'https://example.com/plaid-suit1.jpg',
			'https://example.com/plaid-suit2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Gray'],
		ProductReviewCount: 75,
		ProductStarCount: 3,
		DiscountPrice: 239,
		DiscountPersentage: 14.3,
		stock: 35,
	},
	{
		ProductID: '7',
		ProductTitle: 'Navy Blue Blazer',
		description: 'A classic navy blue blazer for a sophisticated look.',
		Price: 149,
		currency: 'USD',
		category: 'Blazers',
		collection: 'Classic',
		ImageUrl: '/Img/productImages/navy-blue-blazer.png',
		images: [
			'https://example.com/navy-blue-blazer1.jpg',
			'https://example.com/navy-blue-blazer2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Navy'],
		ProductReviewCount: 81,
		ProductStarCount: 4,
		DiscountPrice: 129,
		stock: 40,
	},
	{
		ProductID: '8',
		ProductTitle: 'Slim Fit Gray Suit',
		description: 'A slim fit gray suit for a modern and versatile look.',
		Price: 259,
		currency: 'USD',
		category: 'Suits',
		collection: 'Modern',
		ImageUrl: '/Img/productImages/slim-fit-gray-suit.png',
		images: [
			'https://example.com/slim-gray-suit1.jpg',
			'https://example.com/slim-gray-suit2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Gray'],
		ProductReviewCount: 69,
		ProductStarCount: 5,
		DiscountPrice: 130,
		stock: 30,
	},
	{
		ProductID: '9',
		ProductTitle: 'Checked Tweed Blazer',
		description:
			'A stylish checked tweed blazer for a vintage-inspired look.',
		Price: 179,
		currency: 'USD',
		category: 'Blazers',
		collection: 'Vintage',
		ImageUrl: '/Img/productImages/checked-tweed-blazer.png',
		images: [
			'https://example.com/checked-tweed-blazer1.jpg',
			'https://example.com/checked-tweed-blazer2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Brown', 'Gray'],
		ProductReviewCount: 48,
		ProductStarCount: 4,
		DiscountPrice: 149,
		stock: 25,
	},
	{
		ProductID: '10',
		ProductTitle: 'Lightweight Linen Blazer',
		description: 'A lightweight linen blazer perfect for summer.',
		Price: 129,
		currency: 'USD',
		category: 'Blazers',
		collection: 'Classic',
		ImageUrl: '/Img/productImages/lightweight-linen-blazer.png',
		images: [
			'https://example.com/linen-blazer1.jpg',
			'https://example.com/linen-blazer2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Beige'],
		ProductReviewCount: 63,
		ProductStarCount: 4,
		DiscountPrice: 50,
		stock: 35,
	},
	{
		ProductID: '11',
		ProductTitle: 'Velvet Dinner Jacket',
		description: 'A luxurious velvet dinner jacket for formal occasions.',
		Price: 399,
		currency: 'USD',
		category: 'Blazers',
		collection: 'Formal',
		ImageUrl: '/Img/productImages/velvet-dinner-jacket.jpg',
		images: [
			'https://example.com/velvet-dinner-jacket1.jpg',
			'https://example.com/velvet-dinner-jacket2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Black', 'Burgundy'],
		ProductReviewCount: 55,
		ProductStarCount: 4,
		DiscountPrice: 200,
		stock: 20,
	},
	{
		ProductID: '12',
		ProductTitle: 'Striped Business Suit',
		description:
			'A classic striped business suit for professional settings.',
		Price: 289,
		currency: 'USD',
		category: 'Suits',
		collection: 'Business',
		ImageUrl: '/Img/productImages/striped-business-suit.jpg',
		images: [
			'https://example.com/striped-suit1.jpg',
			'https://example.com/striped-suit2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Navy', 'Gray'],
		ProductReviewCount: 72,
		ProductStarCount: 5,
		DiscountPrice: 249,
		stock: 30,
	},
	{
		ProductID: '13',
		ProductTitle: 'Woolen Overcoat',
		description: 'A warm woolen overcoat for chilly days.',
		Price: 299,
		currency: 'USD',
		category: 'Outerwear',
		collection: 'Formal',
		ImageUrl: '/Img/productImages/woolen-overcoat.jpg',
		images: [
			'https://example.com/woolen-overcoat1.jpg',
			'https://example.com/woolen-overcoat2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Black', 'Gray'],
		ProductReviewCount: 39,
		ProductStarCount: 3,
		DiscountPrice: 259,
		stock: 15,
	},
	{
		ProductID: '14',
		ProductTitle: 'Leather Jacket',
		description: 'A stylish leather jacket for a rugged look.',
		Price: 349,
		currency: 'USD',
		category: 'Outerwear',
		collection: 'Business',
		ImageUrl: '/Img/productImages/leather-jacket.jpg',
		images: [
			'https://example.com/leather-jacket1.jpg',
			'https://example.com/leather-jacket2.jpg',
		],
		ProductSizeArray: ['S', 'M', 'L'],
		colors: ['Black', 'Brown'],
		ProductReviewCount: 59,
		ProductStarCount: 3,
		DiscountPrice: 199,
		stock: 20,
	},
];

export const collections = [
	{
		name: 'Classic',
		description: 'Timeless and elegant suits for any occasion.',
		image: '/Img/CollectionImages/classic-collection.jpg',
	},
	{
		name: 'Modern',
		description: 'Sleek and contemporary suits for the modern man.',
		image: '/Img/CollectionImages/modern-collection.jpg',
	},
	{
		name: 'Vintage',
		description: 'Vintage-inspired suits for a retro look.',
		image: '/Img/CollectionImages/vintage-collection.jpg',
	},
	{
		name: 'Formal',
		description:
			'Elegant tuxedos and formal suits for special occasions.',
		image: '/Img/CollectionImages/formal-collection.jpg',
	},
	{
		name: 'Business',
		description: 'Sophisticated business suits for the professional man.',
		image: '/Img/CollectionImages/business-collection.jpg',
	},
];
