import type { Metadata } from 'next';
import { Cinzel } from 'next/font/google';
import './global.css';

const inter = Cinzel({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'The Classic Edit',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
